apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agent-invest
resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - apps.yaml
  - monitoring.yaml
  - ingress.yaml

