# This file is a TEMPLATE - secrets will be created by create-secrets.sh
# DO NOT manually apply this file - it contains no actual secrets
#
# Usage:
#   ./create-secrets.sh
#
# The script will read your .env files and create the following secrets:
#   - auth-db-credentials: PostgreSQL credentials for auth database
#   - portfolio-db-credentials: PostgreSQL credentials for portfolio database  
#   - auth-env-secret: Environment variables for auth-server
#   - portfolio-env-secret: Environment variables for portfolio-server
#
# All secrets will be created in the agent-invest namespace

